name: Build

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout Remix repo
        uses: actions/checkout@v3
        with:
          repository: 'remix-run/remix'
          fetch-depth: 0

      - name: ⬇️ Checkout remix-azure-functions repo
        uses: actions/checkout@v3
        with:
          path: 'packages/remix-azure-functions'
          fetch-depth: 0

      - name: Apply Remix patch
        run: git apply packages/remix-azure-functions/remix.patch

      - name: ⎔ Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "yarn"

      - name: 📥 Install deps
        run: yarn

      - name: Build
        run: yarn build

      - name: Show build output
        run: ls build/node_modules/*
